// Generated by swift-generator from dzda/imageinfo.thrift

package com.igool.rpc.db.model.thrift;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import java.util.*;
import java.io.*;

import static com.google.common.base.MoreObjects.toStringHelper;

@ThriftStruct("BusinessImageCount")
public final class BusinessImageCount  implements Serializable
{
    public BusinessImageCount() {
    }

    private int xh;

    @ThriftField(value=1, name="xh", requiredness=Requiredness.NONE)
    public int getXh() { return xh; }

    @ThriftField
    public void setXh(final int xh) { this.xh = xh; }

    private String manageDept;

    @ThriftField(value=2, name="manageDept", requiredness=Requiredness.NONE)
    public String getManageDept() { return manageDept; }

    @ThriftField
    public void setManageDept(final String manageDept) { this.manageDept = manageDept; }

    private List<String> businessType;

    @ThriftField(value=3, name="businessType", requiredness=Requiredness.NONE)
    public List<String> getBusinessType() { return businessType; }

    @ThriftField
    public void setBusinessType(final List<String> businessType) { this.businessType = businessType; }

    private List<String> businessNum;

    @ThriftField(value=4, name="businessNum", requiredness=Requiredness.NONE)
    public List<String> getBusinessNum() { return businessNum; }

    @ThriftField
    public void setBusinessNum(final List<String> businessNum) { this.businessNum = businessNum; }

    private int businessCount;

    @ThriftField(value=5, name="businessCount", requiredness=Requiredness.NONE)
    public int getBusinessCount() { return businessCount; }

    @ThriftField
    public void setBusinessCount(final int businessCount) { this.businessCount = businessCount; }

    private int driverCount;

    @ThriftField(value=6, name="driverCount", requiredness=Requiredness.NONE)
    public int getDriverCount() { return driverCount; }

    @ThriftField
    public void setDriverCount(final int driverCount) { this.driverCount = driverCount; }

    @Override
    public String toString()
    {
        return toStringHelper(this)
            .add("xh", xh)
            .add("manageDept", manageDept)
            .add("businessType", businessType)
            .add("businessNum", businessNum)
            .add("businessCount", businessCount)
            .add("driverCount", driverCount)
            .toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        BusinessImageCount other = (BusinessImageCount)o;

        return
            Objects.equals(xh, other.xh) &&
            Objects.equals(manageDept, other.manageDept) &&
            Objects.equals(businessType, other.businessType) &&
            Objects.equals(businessNum, other.businessNum) &&
            Objects.equals(businessCount, other.businessCount) &&
            Objects.equals(driverCount, other.driverCount);
    }

    @Override
    public int hashCode() {
        return Arrays.deepHashCode(new Object[] {
            xh,
            manageDept,
            businessType,
            businessNum,
            businessCount,
            driverCount
        });
    }
}
