// Generated by swift-generator from dzda/businessqszlrel.thrift

package com.igool.rpc.db.model.thrift;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import java.util.*;
import java.io.*;

import static com.google.common.base.MoreObjects.toStringHelper;

@ThriftStruct("BusinessQszlRel")
public final class BusinessQszlRel  implements Serializable
{
    public BusinessQszlRel() {
    }

    private int businessQszlId;

    @ThriftField(value=1, name="businessQszlId", requiredness=Requiredness.NONE)
    public int getBusinessQszlId() { return businessQszlId; }

    @ThriftField
    public void setBusinessQszlId(final int businessQszlId) { this.businessQszlId = businessQszlId; }

    private int businessId;

    @ThriftField(value=2, name="businessId", requiredness=Requiredness.NONE)
    public int getBusinessId() { return businessId; }

    @ThriftField
    public void setBusinessId(final int businessId) { this.businessId = businessId; }

    private int businessDetailId;

    @ThriftField(value=3, name="businessDetailId", requiredness=Requiredness.NONE)
    public int getBusinessDetailId() { return businessDetailId; }

    @ThriftField
    public void setBusinessDetailId(final int businessDetailId) { this.businessDetailId = businessDetailId; }

    private String createTime;

    @ThriftField(value=4, name="createTime", requiredness=Requiredness.NONE)
    public String getCreateTime() { return createTime; }

    @ThriftField
    public void setCreateTime(final String createTime) { this.createTime = createTime; }

    private int createUser;

    @ThriftField(value=5, name="createUser", requiredness=Requiredness.NONE)
    public int getCreateUser() { return createUser; }

    @ThriftField
    public void setCreateUser(final int createUser) { this.createUser = createUser; }

    @Override
    public String toString()
    {
        return toStringHelper(this)
            .add("businessQszlId", businessQszlId)
            .add("businessId", businessId)
            .add("businessDetailId", businessDetailId)
            .add("createTime", createTime)
            .add("createUser", createUser)
            .toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        BusinessQszlRel other = (BusinessQszlRel)o;

        return
            Objects.equals(businessQszlId, other.businessQszlId) &&
            Objects.equals(businessId, other.businessId) &&
            Objects.equals(businessDetailId, other.businessDetailId) &&
            Objects.equals(createTime, other.createTime) &&
            Objects.equals(createUser, other.createUser);
    }

    @Override
    public int hashCode() {
        return Arrays.deepHashCode(new Object[] {
            businessQszlId,
            businessId,
            businessDetailId,
            createTime,
            createUser
        });
    }
}
