// Generated by swift-generator from dzda/fileinfo.thrift

package com.igool.rpc.db.model.thrift;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import java.util.*;
import java.io.*;

import static com.google.common.base.MoreObjects.toStringHelper;

@ThriftStruct("FileInfo")
public final class FileInfo  implements Serializable
{
    public FileInfo() {
    }

    private int fileId;

    @ThriftField(value=1, name="fileId", requiredness=Requiredness.NONE)
    public int getFileId() { return fileId; }

    @ThriftField
    public void setFileId(final int fileId) { this.fileId = fileId; }

    private String fileCode;

    @ThriftField(value=2, name="fileCode", requiredness=Requiredness.NONE)
    public String getFileCode() { return fileCode; }

    @ThriftField
    public void setFileCode(final String fileCode) { this.fileCode = fileCode; }

    private String carCode;

    @ThriftField(value=3, name="carCode", requiredness=Requiredness.NONE)
    public String getCarCode() { return carCode; }

    @ThriftField
    public void setCarCode(final String carCode) { this.carCode = carCode; }

    private String hpzl;

    @ThriftField(value=4, name="hpzl", requiredness=Requiredness.NONE)
    public String getHpzl() { return hpzl; }

    @ThriftField
    public void setHpzl(final String hpzl) { this.hpzl = hpzl; }

    private String hphm;

    @ThriftField(value=5, name="hphm", requiredness=Requiredness.NONE)
    public String getHphm() { return hphm; }

    @ThriftField
    public void setHphm(final String hphm) { this.hphm = hphm; }

    private int status;

    @ThriftField(value=6, name="status", requiredness=Requiredness.NONE)
    public int getStatus() { return status; }

    @ThriftField
    public void setStatus(final int status) { this.status = status; }

    private int ckStatus;

    @ThriftField(value=7, name="ckStatus", requiredness=Requiredness.NONE)
    public int getCkStatus() { return ckStatus; }

    @ThriftField
    public void setCkStatus(final int ckStatus) { this.ckStatus = ckStatus; }

    private String carNumber;

    @ThriftField(value=8, name="carNumber", requiredness=Requiredness.NONE)
    public String getCarNumber() { return carNumber; }

    @ThriftField
    public void setCarNumber(final String carNumber) { this.carNumber = carNumber; }

    @Override
    public String toString()
    {
        return toStringHelper(this)
            .add("fileId", fileId)
            .add("fileCode", fileCode)
            .add("carCode", carCode)
            .add("hpzl", hpzl)
            .add("hphm", hphm)
            .add("status", status)
            .add("ckStatus", ckStatus)
            .add("carNumber", carNumber)
            .toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        FileInfo other = (FileInfo)o;

        return
            Objects.equals(fileId, other.fileId) &&
            Objects.equals(fileCode, other.fileCode) &&
            Objects.equals(carCode, other.carCode) &&
            Objects.equals(hpzl, other.hpzl) &&
            Objects.equals(hphm, other.hphm) &&
            Objects.equals(status, other.status) &&
            Objects.equals(ckStatus, other.ckStatus) &&
            Objects.equals(carNumber, other.carNumber);
    }

    @Override
    public int hashCode() {
        return Arrays.deepHashCode(new Object[] {
            fileId,
            fileCode,
            carCode,
            hpzl,
            hphm,
            status,
            ckStatus,
            carNumber
        });
    }
}
