// Generated by swift-generator from dzda/platetype.thrift

package com.igool.rpc.db.model.thrift;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import java.util.*;
import java.io.*;

import static com.google.common.base.MoreObjects.toStringHelper;

@ThriftStruct("PlateType")
public final class PlateType  implements Serializable
{
    public PlateType() {
    }

    private int id;

    @ThriftField(value=1, name="id", requiredness=Requiredness.NONE)
    public int getId() { return id; }

    @ThriftField
    public void setId(final int id) { this.id = id; }

    private String plateType;

    @ThriftField(value=2, name="plateType", requiredness=Requiredness.NONE)
    public String getPlateType() { return plateType; }

    @ThriftField
    public void setPlateType(final String plateType) { this.plateType = plateType; }

    private String name;

    @ThriftField(value=3, name="name", requiredness=Requiredness.NONE)
    public String getName() { return name; }

    @ThriftField
    public void setName(final String name) { this.name = name; }

    @Override
    public String toString()
    {
        return toStringHelper(this)
            .add("id", id)
            .add("plateType", plateType)
            .add("name", name)
            .toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        PlateType other = (PlateType)o;

        return
            Objects.equals(id, other.id) &&
            Objects.equals(plateType, other.plateType) &&
            Objects.equals(name, other.name);
    }

    @Override
    public int hashCode() {
        return Arrays.deepHashCode(new Object[] {
            id,
            plateType,
            name
        });
    }
}
