// Generated by swift-generator from dzda/signingrel.thrift

package com.igool.rpc.db.model.thrift;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import java.util.*;
import java.io.*;

import static com.google.common.base.MoreObjects.toStringHelper;

@ThriftStruct("SigningRel")
public final class SigningRel  implements Serializable
{
    public SigningRel() {
    }

    private int signingRelId;

    @ThriftField(value=1, name="signingRelId", requiredness=Requiredness.NONE)
    public int getSigningRelId() { return signingRelId; }

    @ThriftField
    public void setSigningRelId(final int signingRelId) { this.signingRelId = signingRelId; }

    private int signingId;

    @ThriftField(value=2, name="signingId", requiredness=Requiredness.NONE)
    public int getSigningId() { return signingId; }

    @ThriftField
    public void setSigningId(final int signingId) { this.signingId = signingId; }

    private int fileId;

    @ThriftField(value=3, name="fileId", requiredness=Requiredness.NONE)
    public int getFileId() { return fileId; }

    @ThriftField
    public void setFileId(final int fileId) { this.fileId = fileId; }

    private String createDate;

    @ThriftField(value=4, name="createDate", requiredness=Requiredness.NONE)
    public String getCreateDate() { return createDate; }

    @ThriftField
    public void setCreateDate(final String createDate) { this.createDate = createDate; }

    private int createUser;

    @ThriftField(value=5, name="createUser", requiredness=Requiredness.NONE)
    public int getCreateUser() { return createUser; }

    @ThriftField
    public void setCreateUser(final int createUser) { this.createUser = createUser; }

    private int status;

    @ThriftField(value=6, name="status", requiredness=Requiredness.NONE)
    public int getStatus() { return status; }

    @ThriftField
    public void setStatus(final int status) { this.status = status; }

    private int businessId;

    @ThriftField(value=7, name="businessId", requiredness=Requiredness.NONE)
    public int getBusinessId() { return businessId; }

    @ThriftField
    public void setBusinessId(final int businessId) { this.businessId = businessId; }

    @Override
    public String toString()
    {
        return toStringHelper(this)
            .add("signingRelId", signingRelId)
            .add("signingId", signingId)
            .add("fileId", fileId)
            .add("createDate", createDate)
            .add("createUser", createUser)
            .add("status", status)
            .add("businessId", businessId)
            .toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        SigningRel other = (SigningRel)o;

        return
            Objects.equals(signingRelId, other.signingRelId) &&
            Objects.equals(signingId, other.signingId) &&
            Objects.equals(fileId, other.fileId) &&
            Objects.equals(createDate, other.createDate) &&
            Objects.equals(createUser, other.createUser) &&
            Objects.equals(status, other.status) &&
            Objects.equals(businessId, other.businessId);
    }

    @Override
    public int hashCode() {
        return Arrays.deepHashCode(new Object[] {
            signingRelId,
            signingId,
            fileId,
            createDate,
            createUser,
            status,
            businessId
        });
    }
}
