// Generated by swift-generator from dzda/vehicledetail.thrift

package com.igool.rpc.db.model.thrift;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import java.util.*;
import java.io.*;

import static com.google.common.base.MoreObjects.toStringHelper;

@ThriftStruct("VehicleDetail")
public final class VehicleDetail  implements Serializable
{
    public VehicleDetail() {
    }

    private String syr;

    @ThriftField(value=1, name="syr", requiredness=Requiredness.NONE)
    public String getSyr() { return syr; }

    @ThriftField
    public void setSyr(final String syr) { this.syr = syr; }

    private String hphm;

    @ThriftField(value=2, name="hphm", requiredness=Requiredness.NONE)
    public String getHphm() { return hphm; }

    @ThriftField
    public void setHphm(final String hphm) { this.hphm = hphm; }

    private String clsbdh;

    @ThriftField(value=3, name="clsbdh", requiredness=Requiredness.NONE)
    public String getClsbdh() { return clsbdh; }

    @ThriftField
    public void setClsbdh(final String clsbdh) { this.clsbdh = clsbdh; }

    private String fdjh;

    @ThriftField(value=4, name="fdjh", requiredness=Requiredness.NONE)
    public String getFdjh() { return fdjh; }

    @ThriftField
    public void setFdjh(final String fdjh) { this.fdjh = fdjh; }

    private String hpzl;

    @ThriftField(value=5, name="hpzl", requiredness=Requiredness.NONE)
    public String getHpzl() { return hpzl; }

    @ThriftField
    public void setHpzl(final String hpzl) { this.hpzl = hpzl; }

    private String cllx;

    @ThriftField(value=6, name="cllx", requiredness=Requiredness.NONE)
    public String getCllx() { return cllx; }

    @ThriftField
    public void setCllx(final String cllx) { this.cllx = cllx; }

    private String clxh;

    @ThriftField(value=7, name="clxh", requiredness=Requiredness.NONE)
    public String getClxh() { return clxh; }

    @ThriftField
    public void setClxh(final String clxh) { this.clxh = clxh; }

    private String csys;

    @ThriftField(value=8, name="csys", requiredness=Requiredness.NONE)
    public String getCsys() { return csys; }

    @ThriftField
    public void setCsys(final String csys) { this.csys = csys; }

    private String syxz;

    @ThriftField(value=9, name="syxz", requiredness=Requiredness.NONE)
    public String getSyxz() { return syxz; }

    @ThriftField
    public void setSyxz(final String syxz) { this.syxz = syxz; }

    private String zt;

    @ThriftField(value=10, name="zt", requiredness=Requiredness.NONE)
    public String getZt() { return zt; }

    @ThriftField
    public void setZt(final String zt) { this.zt = zt; }

    private String ccdjrq;

    @ThriftField(value=11, name="ccdjrq", requiredness=Requiredness.NONE)
    public String getCcdjrq() { return ccdjrq; }

    @ThriftField
    public void setCcdjrq(final String ccdjrq) { this.ccdjrq = ccdjrq; }

    private String yxqz;

    @ThriftField(value=12, name="yxqz", requiredness=Requiredness.NONE)
    public String getYxqz() { return yxqz; }

    @ThriftField
    public void setYxqz(final String yxqz) { this.yxqz = yxqz; }

    private String sjhm;

    @ThriftField(value=13, name="sjhm", requiredness=Requiredness.NONE)
    public String getSjhm() { return sjhm; }

    @ThriftField
    public void setSjhm(final String sjhm) { this.sjhm = sjhm; }

    private String dabh;

    @ThriftField(value=14, name="dabh", requiredness=Requiredness.NONE)
    public String getDabh() { return dabh; }

    @ThriftField
    public void setDabh(final String dabh) { this.dabh = dabh; }

    private List<VehicleFlow> vehicleFlows;

    @ThriftField(value=15, name="vehicleFlows", requiredness=Requiredness.NONE)
    public List<VehicleFlow> getVehicleFlows() { return vehicleFlows; }

    @ThriftField
    public void setVehicleFlows(final List<VehicleFlow> vehicleFlows) { this.vehicleFlows = vehicleFlows; }

    private String sfz;

    @ThriftField(value=16, name="sfz", requiredness=Requiredness.NONE)
    public String getSfz() { return sfz; }

    @ThriftField
    public void setSfz(final String sfz) { this.sfz = sfz; }

    @Override
    public String toString()
    {
        return toStringHelper(this)
            .add("syr", syr)
            .add("hphm", hphm)
            .add("clsbdh", clsbdh)
            .add("fdjh", fdjh)
            .add("hpzl", hpzl)
            .add("cllx", cllx)
            .add("clxh", clxh)
            .add("csys", csys)
            .add("syxz", syxz)
            .add("zt", zt)
            .add("ccdjrq", ccdjrq)
            .add("yxqz", yxqz)
            .add("sjhm", sjhm)
            .add("dabh", dabh)
            .add("vehicleFlows", vehicleFlows)
            .add("sfz", sfz)
            .toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        VehicleDetail other = (VehicleDetail)o;

        return
            Objects.equals(syr, other.syr) &&
            Objects.equals(hphm, other.hphm) &&
            Objects.equals(clsbdh, other.clsbdh) &&
            Objects.equals(fdjh, other.fdjh) &&
            Objects.equals(hpzl, other.hpzl) &&
            Objects.equals(cllx, other.cllx) &&
            Objects.equals(clxh, other.clxh) &&
            Objects.equals(csys, other.csys) &&
            Objects.equals(syxz, other.syxz) &&
            Objects.equals(zt, other.zt) &&
            Objects.equals(ccdjrq, other.ccdjrq) &&
            Objects.equals(yxqz, other.yxqz) &&
            Objects.equals(sjhm, other.sjhm) &&
            Objects.equals(dabh, other.dabh) &&
            Objects.equals(vehicleFlows, other.vehicleFlows) &&
            Objects.equals(sfz, other.sfz);
    }

    @Override
    public int hashCode() {
        return Arrays.deepHashCode(new Object[] {
            syr,
            hphm,
            clsbdh,
            fdjh,
            hpzl,
            cllx,
            clxh,
            csys,
            syxz,
            zt,
            ccdjrq,
            yxqz,
            sjhm,
            dabh,
            vehicleFlows,
            sfz
        });
    }
}
