// Generated by swift-generator from dzda/wtda.thrift

package com.igool.rpc.db.model.thrift;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import java.util.*;
import java.io.*;

import static com.google.common.base.MoreObjects.toStringHelper;

@ThriftStruct("Wtda")
public final class Wtda  implements Serializable
{
    public Wtda() {
    }

    private String fileCode;

    @ThriftField(value=1, name="fileCode", requiredness=Requiredness.NONE)
    public String getFileCode() { return fileCode; }

    @ThriftField
    public void setFileCode(final String fileCode) { this.fileCode = fileCode; }

    private String businessCode;

    @ThriftField(value=2, name="businessCode", requiredness=Requiredness.NONE)
    public String getBusinessCode() { return businessCode; }

    @ThriftField
    public void setBusinessCode(final String businessCode) { this.businessCode = businessCode; }

    private int qsStatus;

    @ThriftField(value=3, name="qsStatus", requiredness=Requiredness.NONE)
    public int getQsStatus() { return qsStatus; }

    @ThriftField
    public void setQsStatus(final int qsStatus) { this.qsStatus = qsStatus; }

    private String qsStatusStr;

    @ThriftField(value=4, name="qsStatusStr", requiredness=Requiredness.NONE)
    public String getQsStatusStr() { return qsStatusStr; }

    @ThriftField
    public void setQsStatusStr(final String qsStatusStr) { this.qsStatusStr = qsStatusStr; }

    private String qsDetail;

    @ThriftField(value=5, name="qsDetail", requiredness=Requiredness.NONE)
    public String getQsDetail() { return qsDetail; }

    @ThriftField
    public void setQsDetail(final String qsDetail) { this.qsDetail = qsDetail; }

    @Override
    public String toString()
    {
        return toStringHelper(this)
            .add("fileCode", fileCode)
            .add("businessCode", businessCode)
            .add("qsStatus", qsStatus)
            .add("qsStatusStr", qsStatusStr)
            .add("qsDetail", qsDetail)
            .toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        Wtda other = (Wtda)o;

        return
            Objects.equals(fileCode, other.fileCode) &&
            Objects.equals(businessCode, other.businessCode) &&
            Objects.equals(qsStatus, other.qsStatus) &&
            Objects.equals(qsStatusStr, other.qsStatusStr) &&
            Objects.equals(qsDetail, other.qsDetail);
    }

    @Override
    public int hashCode() {
        return Arrays.deepHashCode(new Object[] {
            fileCode,
            businessCode,
            qsStatus,
            qsStatusStr,
            qsDetail
        });
    }
}
