// Generated by swift-generator from id.thrift

package com.igool.id.service.thrift;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.service.*;
import com.google.common.util.concurrent.ListenableFuture;
import java.io.*;
import java.util.*;


@ThriftService("IdGenerateService")
public interface IdGenerateService extends Closeable
{
    @ThriftService("IdGenerateService")
    public interface Async extends Closeable
    {
        void close();

        @ThriftMethod(value = "getGenerateIdByName")
        ListenableFuture<Long> getGenerateIdByName(
            @ThriftField(value=1, name="name", requiredness=Requiredness.NONE) final String name
        );
    }
    void close();


    @ThriftMethod(value = "getGenerateIdByName")
    long getGenerateIdByName(
        @ThriftField(value=1, name="name", requiredness=Requiredness.NONE) final String name
    ) throws org.apache.thrift.TException;
}