// Generated by swift-generator from dzda/businesstypeservice.thrift

package com.igool.rpc.db.service.thrift;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.service.*;
import com.google.common.util.concurrent.ListenableFuture;
import java.io.*;
import java.util.*;


@ThriftService("BusinessTypeService")
public interface BusinessTypeService extends Closeable
{
    @ThriftService("BusinessTypeService")
    public interface Async extends Closeable
    {
        void close();

        @ThriftMethod(value = "getAllBusinessType")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.BusinessTypeInfo>> getAllBusinessType();

        @ThriftMethod(value = "findBusinessTypeDetailByYwlx")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.BusinessTypeDetail>> findBusinessTypeDetailByYwlx(
            @ThriftField(value=1, name="ywlx", requiredness=Requiredness.NONE) final String ywlx
        );

        @ThriftMethod(value = "findBusinessTypeByYwlx")
        ListenableFuture<com.igool.rpc.db.model.thrift.BusinessTypeInfo> findBusinessTypeByYwlx(
            @ThriftField(value=1, name="ywlx", requiredness=Requiredness.NONE) final String ywlx
        );

        @ThriftMethod(value = "findBusinessTypeDetailAllBybusinessCode")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.BusinessTypeDetail>> findBusinessTypeDetailAllBybusinessCode(
            @ThriftField(value=1, name="lsh", requiredness=Requiredness.NONE) final String lsh
        );

        @ThriftMethod(value = "findBusinessTypeByLsh")
        ListenableFuture<com.igool.rpc.db.model.thrift.BusinessTypeInfo> findBusinessTypeByLsh(
            @ThriftField(value=1, name="lsh", requiredness=Requiredness.NONE) final String lsh
        );
    }
    void close();


    @ThriftMethod(value = "getAllBusinessType")
    List<com.igool.rpc.db.model.thrift.BusinessTypeInfo> getAllBusinessType() throws org.apache.thrift.TException;

    @ThriftMethod(value = "findBusinessTypeDetailByYwlx")
    List<com.igool.rpc.db.model.thrift.BusinessTypeDetail> findBusinessTypeDetailByYwlx(
        @ThriftField(value=1, name="ywlx", requiredness=Requiredness.NONE) final String ywlx
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "findBusinessTypeByYwlx")
    com.igool.rpc.db.model.thrift.BusinessTypeInfo findBusinessTypeByYwlx(
        @ThriftField(value=1, name="ywlx", requiredness=Requiredness.NONE) final String ywlx
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "findBusinessTypeDetailAllBybusinessCode")
    List<com.igool.rpc.db.model.thrift.BusinessTypeDetail> findBusinessTypeDetailAllBybusinessCode(
        @ThriftField(value=1, name="lsh", requiredness=Requiredness.NONE) final String lsh
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "findBusinessTypeByLsh")
    com.igool.rpc.db.model.thrift.BusinessTypeInfo findBusinessTypeByLsh(
        @ThriftField(value=1, name="lsh", requiredness=Requiredness.NONE) final String lsh
    ) throws org.apache.thrift.TException;
}