// Generated by swift-generator from dzda/businessinfoservice.thrift

package com.igool.rpc.db.service.thrift;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.service.*;
import com.google.common.util.concurrent.ListenableFuture;
import java.io.*;
import java.util.*;


@ThriftService("BusinessInfoService")
public interface BusinessInfoService extends Closeable
{
    @ThriftService("BusinessInfoService")
    public interface Async extends Closeable
    {
        void close();

        @ThriftMethod(value = "findBusinessInfoByCode")
        ListenableFuture<com.igool.rpc.db.model.thrift.BusinessInfo> findBusinessInfoByCode(
            @ThriftField(value=1, name="code", requiredness=Requiredness.NONE) final String code
        );

        @ThriftMethod(value = "deleteBusinessInfo")
        ListenableFuture<Void> deleteBusinessInfo(
            @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo
        );

        @ThriftMethod(value = "getBusinessInfoList")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.BusinessInfo>> getBusinessInfoList(
            @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo,
            @ThriftField(value=2, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
            @ThriftField(value=3, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
        );

        @ThriftMethod(value = "getBusinessInfoListCount")
        ListenableFuture<Long> getBusinessInfoListCount(
            @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo,
            @ThriftField(value=2, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
            @ThriftField(value=3, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
        );

        @ThriftMethod(value = "getBusinessInfoListForShow")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.BusinessInfo>> getBusinessInfoListForShow(
            @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo,
            @ThriftField(value=2, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
            @ThriftField(value=3, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
        );

        @ThriftMethod(value = "getBusinessInfoListForShowCount")
        ListenableFuture<Long> getBusinessInfoListForShowCount(
            @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo,
            @ThriftField(value=2, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
            @ThriftField(value=3, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
        );

        @ThriftMethod(value = "getWtdaList")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.Wtda>> getWtdaList(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
            @ThriftField(value=3, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
            @ThriftField(value=4, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
        );

        @ThriftMethod(value = "getWtdaListCount")
        ListenableFuture<Long> getWtdaListCount(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
            @ThriftField(value=3, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
            @ThriftField(value=4, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
        );

        @ThriftMethod(value = "getDeliveryList")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.Jjtj>> getDeliveryList(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime
        );

        @ThriftMethod(value = "getDeliveryAndSignList")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.Jjtj>> getDeliveryAndSignList(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
            @ThriftField(value=3, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
            @ThriftField(value=4, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
        );

        @ThriftMethod(value = "getDeliveryAndSignListCount")
        ListenableFuture<Long> getDeliveryAndSignListCount(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
            @ThriftField(value=3, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
            @ThriftField(value=4, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
        );

        @ThriftMethod(value = "getSignList")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.Jjtj>> getSignList(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime
        );

        @ThriftMethod(value = "getOldDeliveryList")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.Jjtj>> getOldDeliveryList(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime
        );

        @ThriftMethod(value = "getOldSignList")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.Jjtj>> getOldSignList(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime
        );

        @ThriftMethod(value = "getOldLsmxList")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.Lsmx>> getOldLsmxList(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
            @ThriftField(value=3, name="jjlx", requiredness=Requiredness.NONE) final int jjlx
        );

        @ThriftMethod(value = "getOldDamxList")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.Lsmx>> getOldDamxList(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
            @ThriftField(value=3, name="jjlx", requiredness=Requiredness.NONE) final int jjlx
        );

        @ThriftMethod(value = "getNewLsmxList")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.Lsmx>> getNewLsmxList(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
            @ThriftField(value=3, name="jjlx", requiredness=Requiredness.NONE) final int jjlx,
            @ThriftField(value=4, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
            @ThriftField(value=5, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
        );

        @ThriftMethod(value = "getNewDamxList")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.Lsmx>> getNewDamxList(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
            @ThriftField(value=3, name="jjlx", requiredness=Requiredness.NONE) final int jjlx,
            @ThriftField(value=4, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
            @ThriftField(value=5, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
        );

        @ThriftMethod(value = "addAToBRegister")
        ListenableFuture<com.igool.rpc.db.model.thrift.DeliveryInfo> addAToBRegister(
            @ThriftField(value=1, name="businessInfos", requiredness=Requiredness.NONE) final List<com.igool.rpc.db.model.thrift.BusinessInfo> businessInfos,
            @ThriftField(value=2, name="box", requiredness=Requiredness.NONE) final String box,
            @ThriftField(value=3, name="userId", requiredness=Requiredness.NONE) final int userId
        );

        @ThriftMethod(value = "findNativeBusinessInfoByLsh")
        ListenableFuture<com.igool.rpc.db.model.thrift.BusinessInfo> findNativeBusinessInfoByLsh(
            @ThriftField(value=1, name="lsh", requiredness=Requiredness.NONE) final String lsh
        );

        @ThriftMethod(value = "BToARegister")
        ListenableFuture<String> BToARegister(
            @ThriftField(value=1, name="businessInfos", requiredness=Requiredness.NONE) final List<com.igool.rpc.db.model.thrift.BusinessInfo> businessInfos,
            @ThriftField(value=2, name="userId", requiredness=Requiredness.NONE) final int userId
        );

        @ThriftMethod(value = "findNativeBusinessInfoByDeliveryPcCode")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.BusinessInfo>> findNativeBusinessInfoByDeliveryPcCode(
            @ThriftField(value=1, name="pcCode", requiredness=Requiredness.NONE) final String pcCode
        );

        @ThriftMethod(value = "saveBusinessInfo")
        ListenableFuture<Integer> saveBusinessInfo(
            @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo
        );

        @ThriftMethod(value = "findDeliveryByCodeAndBoxAndDate")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.DeliveryInfo>> findDeliveryByCodeAndBoxAndDate(
            @ThriftField(value=1, name="code", requiredness=Requiredness.NONE) final String code,
            @ThriftField(value=2, name="box", requiredness=Requiredness.NONE) final String box,
            @ThriftField(value=3, name="start", requiredness=Requiredness.NONE) final String start,
            @ThriftField(value=4, name="end", requiredness=Requiredness.NONE) final String end,
            @ThriftField(value=5, name="indexPage", requiredness=Requiredness.NONE) final int indexPage,
            @ThriftField(value=6, name="pageCount", requiredness=Requiredness.NONE) final int pageCount
        );

        @ThriftMethod(value = "findDeliveryByCodeAndBoxAndDateCount")
        ListenableFuture<Long> findDeliveryByCodeAndBoxAndDateCount(
            @ThriftField(value=1, name="code", requiredness=Requiredness.NONE) final String code,
            @ThriftField(value=2, name="box", requiredness=Requiredness.NONE) final String box,
            @ThriftField(value=3, name="start", requiredness=Requiredness.NONE) final String start,
            @ThriftField(value=4, name="end", requiredness=Requiredness.NONE) final String end,
            @ThriftField(value=5, name="indexPage", requiredness=Requiredness.NONE) final int indexPage,
            @ThriftField(value=6, name="pageCount", requiredness=Requiredness.NONE) final int pageCount
        );

        @ThriftMethod(value = "getJjlxByCodes")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.DeliveryInfo>> getJjlxByCodes(
            @ThriftField(value=1, name="deliveryinfos", requiredness=Requiredness.NONE) final List<com.igool.rpc.db.model.thrift.DeliveryInfo> deliveryinfos
        );

        @ThriftMethod(value = "ajaxLookSignDetailByCode")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.BusinessInfo>> ajaxLookSignDetailByCode(
            @ThriftField(value=1, name="code", requiredness=Requiredness.NONE) final String code,
            @ThriftField(value=2, name="bs", requiredness=Requiredness.NONE) final String bs
        );

        @ThriftMethod(value = "findBoxByDeliveryIdAndLsh")
        ListenableFuture<com.igool.rpc.db.model.thrift.BusinessInfo> findBoxByDeliveryIdAndLsh(
            @ThriftField(value=1, name="code", requiredness=Requiredness.NONE) final String code,
            @ThriftField(value=2, name="deliveryId", requiredness=Requiredness.NONE) final String deliveryId
        );

        @ThriftMethod(value = "signBoxInAToB")
        ListenableFuture<Integer> signBoxInAToB(
            @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo,
            @ThriftField(value=2, name="userId", requiredness=Requiredness.NONE) final int userId,
            @ThriftField(value=3, name="deliveryId", requiredness=Requiredness.NONE) final String deliveryId
        );

        @ThriftMethod(value = "getBusinessInfoListByDateOrCodeRefUser")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.DeliveryInfo>> getBusinessInfoListByDateOrCodeRefUser(
            @ThriftField(value=1, name="code", requiredness=Requiredness.NONE) final String code,
            @ThriftField(value=2, name="user", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.UserInfo user,
            @ThriftField(value=3, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=4, name="endTime", requiredness=Requiredness.NONE) final String endTime,
            @ThriftField(value=5, name="indexPage", requiredness=Requiredness.NONE) final int indexPage,
            @ThriftField(value=6, name="pageCount", requiredness=Requiredness.NONE) final int pageCount,
            @ThriftField(value=7, name="users", requiredness=Requiredness.NONE) final List<com.igool.rpc.db.model.thrift.UserInfo> users
        );

        @ThriftMethod(value = "getBusinessInfoListByDateOrCodeRefUserCount")
        ListenableFuture<Integer> getBusinessInfoListByDateOrCodeRefUserCount(
            @ThriftField(value=1, name="code", requiredness=Requiredness.NONE) final String code,
            @ThriftField(value=2, name="user", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.UserInfo user,
            @ThriftField(value=3, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=4, name="endTime", requiredness=Requiredness.NONE) final String endTime,
            @ThriftField(value=7, name="users", requiredness=Requiredness.NONE) final List<com.igool.rpc.db.model.thrift.UserInfo> users
        );

        @ThriftMethod(value = "updateBox")
        ListenableFuture<Integer> updateBox(
            @ThriftField(value=1, name="box", requiredness=Requiredness.NONE) final String box,
            @ThriftField(value=2, name="beforeBox", requiredness=Requiredness.NONE) final String beforeBox
        );

        @ThriftMethod(value = "getBusinessInfoListByBox")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.BusinessInfo>> getBusinessInfoListByBox(
            @ThriftField(value=1, name="box", requiredness=Requiredness.NONE) final String box,
            @ThriftField(value=2, name="deliveryId", requiredness=Requiredness.NONE) final String deliveryId,
            @ThriftField(value=3, name="deliveryCode", requiredness=Requiredness.NONE) final String deliveryCode
        );

        @ThriftMethod(value = "delDeliveryRel")
        ListenableFuture<Void> delDeliveryRel(
            @ThriftField(value=1, name="ids", requiredness=Requiredness.NONE) final String ids,
            @ThriftField(value=2, name="box", requiredness=Requiredness.NONE) final String box,
            @ThriftField(value=3, name="deliveryId", requiredness=Requiredness.NONE) final String deliveryId,
            @ThriftField(value=4, name="userId", requiredness=Requiredness.NONE) final int userId,
            @ThriftField(value=5, name="deliveryCode", requiredness=Requiredness.NONE) final String deliveryCode
        );

        @ThriftMethod(value = "getBusinessInfoListForImage")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.BusinessInfo>> getBusinessInfoListForImage(
            @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo,
            @ThriftField(value=2, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
            @ThriftField(value=3, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
        );

        @ThriftMethod(value = "getBusinessInfoListForImageCount")
        ListenableFuture<Long> getBusinessInfoListForImageCount(
            @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo,
            @ThriftField(value=2, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
            @ThriftField(value=3, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
        );

        @ThriftMethod(value = "updateQsZl")
        ListenableFuture<Void> updateQsZl(
            @ThriftField(value=1, name="businessId", requiredness=Requiredness.NONE) final String businessId,
            @ThriftField(value=2, name="businessDetailIds", requiredness=Requiredness.NONE) final String businessDetailIds,
            @ThriftField(value=3, name="userId", requiredness=Requiredness.NONE) final int userId,
            @ThriftField(value=4, name="fileId", requiredness=Requiredness.NONE) final String fileId
        );

        @ThriftMethod(value = "addBusinessQszl")
        ListenableFuture<Void> addBusinessQszl(
            @ThriftField(value=1, name="lsh", requiredness=Requiredness.NONE) final String lsh,
            @ThriftField(value=2, name="userId", requiredness=Requiredness.NONE) final String userId
        );

        @ThriftMethod(value = "findBusinessIdAndImageIdAndBusinessTypeIdByLsh")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.BusinessImageDTO>> findBusinessIdAndImageIdAndBusinessTypeIdByLsh(
            @ThriftField(value=1, name="lsh", requiredness=Requiredness.NONE) final String lsh
        );

        @ThriftMethod(value = "addFileInfo")
        ListenableFuture<Integer> addFileInfo(
            @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo
        );

        @ThriftMethod(value = "getJxrwqsList")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.Jjtj>> getJxrwqsList(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime
        );

        @ThriftMethod(value = "findFileInfoByBox")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.BusinessInfo>> findFileInfoByBox(
            @ThriftField(value=1, name="box", requiredness=Requiredness.NONE) final String box
        );

        @ThriftMethod(value = "findNotSignCodeByBox")
        ListenableFuture<List<String>> findNotSignCodeByBox(
            @ThriftField(value=1, name="box", requiredness=Requiredness.NONE) final String box
        );

        @ThriftMethod(value = "getNewLsmxListCount")
        ListenableFuture<Long> getNewLsmxListCount(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
            @ThriftField(value=3, name="jjlx", requiredness=Requiredness.NONE) final int jjlx,
            @ThriftField(value=4, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
            @ThriftField(value=5, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
        );

        @ThriftMethod(value = "getNewDamxListCount")
        ListenableFuture<Long> getNewDamxListCount(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
            @ThriftField(value=3, name="jjlx", requiredness=Requiredness.NONE) final int jjlx,
            @ThriftField(value=4, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
            @ThriftField(value=5, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
        );
    }
    void close();


    @ThriftMethod(value = "findBusinessInfoByCode")
    com.igool.rpc.db.model.thrift.BusinessInfo findBusinessInfoByCode(
        @ThriftField(value=1, name="code", requiredness=Requiredness.NONE) final String code
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "deleteBusinessInfo")
    void deleteBusinessInfo(
        @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getBusinessInfoList")
    List<com.igool.rpc.db.model.thrift.BusinessInfo> getBusinessInfoList(
        @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo,
        @ThriftField(value=2, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
        @ThriftField(value=3, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getBusinessInfoListCount")
    long getBusinessInfoListCount(
        @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo,
        @ThriftField(value=2, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
        @ThriftField(value=3, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getBusinessInfoListForShow")
    List<com.igool.rpc.db.model.thrift.BusinessInfo> getBusinessInfoListForShow(
        @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo,
        @ThriftField(value=2, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
        @ThriftField(value=3, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getBusinessInfoListForShowCount")
    long getBusinessInfoListForShowCount(
        @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo,
        @ThriftField(value=2, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
        @ThriftField(value=3, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getWtdaList")
    List<com.igool.rpc.db.model.thrift.Wtda> getWtdaList(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
        @ThriftField(value=3, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
        @ThriftField(value=4, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getWtdaListCount")
    long getWtdaListCount(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
        @ThriftField(value=3, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
        @ThriftField(value=4, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getDeliveryList")
    List<com.igool.rpc.db.model.thrift.Jjtj> getDeliveryList(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getDeliveryAndSignList")
    List<com.igool.rpc.db.model.thrift.Jjtj> getDeliveryAndSignList(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
        @ThriftField(value=3, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
        @ThriftField(value=4, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getDeliveryAndSignListCount")
    long getDeliveryAndSignListCount(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
        @ThriftField(value=3, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
        @ThriftField(value=4, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getSignList")
    List<com.igool.rpc.db.model.thrift.Jjtj> getSignList(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getOldDeliveryList")
    List<com.igool.rpc.db.model.thrift.Jjtj> getOldDeliveryList(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getOldSignList")
    List<com.igool.rpc.db.model.thrift.Jjtj> getOldSignList(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getOldLsmxList")
    List<com.igool.rpc.db.model.thrift.Lsmx> getOldLsmxList(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
        @ThriftField(value=3, name="jjlx", requiredness=Requiredness.NONE) final int jjlx
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getOldDamxList")
    List<com.igool.rpc.db.model.thrift.Lsmx> getOldDamxList(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
        @ThriftField(value=3, name="jjlx", requiredness=Requiredness.NONE) final int jjlx
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getNewLsmxList")
    List<com.igool.rpc.db.model.thrift.Lsmx> getNewLsmxList(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
        @ThriftField(value=3, name="jjlx", requiredness=Requiredness.NONE) final int jjlx,
        @ThriftField(value=4, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
        @ThriftField(value=5, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getNewDamxList")
    List<com.igool.rpc.db.model.thrift.Lsmx> getNewDamxList(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
        @ThriftField(value=3, name="jjlx", requiredness=Requiredness.NONE) final int jjlx,
        @ThriftField(value=4, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
        @ThriftField(value=5, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "addAToBRegister")
    com.igool.rpc.db.model.thrift.DeliveryInfo addAToBRegister(
        @ThriftField(value=1, name="businessInfos", requiredness=Requiredness.NONE) final List<com.igool.rpc.db.model.thrift.BusinessInfo> businessInfos,
        @ThriftField(value=2, name="box", requiredness=Requiredness.NONE) final String box,
        @ThriftField(value=3, name="userId", requiredness=Requiredness.NONE) final int userId
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "findNativeBusinessInfoByLsh")
    com.igool.rpc.db.model.thrift.BusinessInfo findNativeBusinessInfoByLsh(
        @ThriftField(value=1, name="lsh", requiredness=Requiredness.NONE) final String lsh
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "BToARegister")
    String BToARegister(
        @ThriftField(value=1, name="businessInfos", requiredness=Requiredness.NONE) final List<com.igool.rpc.db.model.thrift.BusinessInfo> businessInfos,
        @ThriftField(value=2, name="userId", requiredness=Requiredness.NONE) final int userId
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "findNativeBusinessInfoByDeliveryPcCode")
    List<com.igool.rpc.db.model.thrift.BusinessInfo> findNativeBusinessInfoByDeliveryPcCode(
        @ThriftField(value=1, name="pcCode", requiredness=Requiredness.NONE) final String pcCode
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "saveBusinessInfo")
    int saveBusinessInfo(
        @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "findDeliveryByCodeAndBoxAndDate")
    List<com.igool.rpc.db.model.thrift.DeliveryInfo> findDeliveryByCodeAndBoxAndDate(
        @ThriftField(value=1, name="code", requiredness=Requiredness.NONE) final String code,
        @ThriftField(value=2, name="box", requiredness=Requiredness.NONE) final String box,
        @ThriftField(value=3, name="start", requiredness=Requiredness.NONE) final String start,
        @ThriftField(value=4, name="end", requiredness=Requiredness.NONE) final String end,
        @ThriftField(value=5, name="indexPage", requiredness=Requiredness.NONE) final int indexPage,
        @ThriftField(value=6, name="pageCount", requiredness=Requiredness.NONE) final int pageCount
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "findDeliveryByCodeAndBoxAndDateCount")
    long findDeliveryByCodeAndBoxAndDateCount(
        @ThriftField(value=1, name="code", requiredness=Requiredness.NONE) final String code,
        @ThriftField(value=2, name="box", requiredness=Requiredness.NONE) final String box,
        @ThriftField(value=3, name="start", requiredness=Requiredness.NONE) final String start,
        @ThriftField(value=4, name="end", requiredness=Requiredness.NONE) final String end,
        @ThriftField(value=5, name="indexPage", requiredness=Requiredness.NONE) final int indexPage,
        @ThriftField(value=6, name="pageCount", requiredness=Requiredness.NONE) final int pageCount
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getJjlxByCodes")
    List<com.igool.rpc.db.model.thrift.DeliveryInfo> getJjlxByCodes(
        @ThriftField(value=1, name="deliveryinfos", requiredness=Requiredness.NONE) final List<com.igool.rpc.db.model.thrift.DeliveryInfo> deliveryinfos
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "ajaxLookSignDetailByCode")
    List<com.igool.rpc.db.model.thrift.BusinessInfo> ajaxLookSignDetailByCode(
        @ThriftField(value=1, name="code", requiredness=Requiredness.NONE) final String code,
        @ThriftField(value=2, name="bs", requiredness=Requiredness.NONE) final String bs
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "findBoxByDeliveryIdAndLsh")
    com.igool.rpc.db.model.thrift.BusinessInfo findBoxByDeliveryIdAndLsh(
        @ThriftField(value=1, name="code", requiredness=Requiredness.NONE) final String code,
        @ThriftField(value=2, name="deliveryId", requiredness=Requiredness.NONE) final String deliveryId
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "signBoxInAToB")
    int signBoxInAToB(
        @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo,
        @ThriftField(value=2, name="userId", requiredness=Requiredness.NONE) final int userId,
        @ThriftField(value=3, name="deliveryId", requiredness=Requiredness.NONE) final String deliveryId
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getBusinessInfoListByDateOrCodeRefUser")
    List<com.igool.rpc.db.model.thrift.DeliveryInfo> getBusinessInfoListByDateOrCodeRefUser(
        @ThriftField(value=1, name="code", requiredness=Requiredness.NONE) final String code,
        @ThriftField(value=2, name="user", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.UserInfo user,
        @ThriftField(value=3, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=4, name="endTime", requiredness=Requiredness.NONE) final String endTime,
        @ThriftField(value=5, name="indexPage", requiredness=Requiredness.NONE) final int indexPage,
        @ThriftField(value=6, name="pageCount", requiredness=Requiredness.NONE) final int pageCount,
        @ThriftField(value=7, name="users", requiredness=Requiredness.NONE) final List<com.igool.rpc.db.model.thrift.UserInfo> users
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getBusinessInfoListByDateOrCodeRefUserCount")
    int getBusinessInfoListByDateOrCodeRefUserCount(
        @ThriftField(value=1, name="code", requiredness=Requiredness.NONE) final String code,
        @ThriftField(value=2, name="user", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.UserInfo user,
        @ThriftField(value=3, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=4, name="endTime", requiredness=Requiredness.NONE) final String endTime,
        @ThriftField(value=7, name="users", requiredness=Requiredness.NONE) final List<com.igool.rpc.db.model.thrift.UserInfo> users
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "updateBox")
    int updateBox(
        @ThriftField(value=1, name="box", requiredness=Requiredness.NONE) final String box,
        @ThriftField(value=2, name="beforeBox", requiredness=Requiredness.NONE) final String beforeBox
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getBusinessInfoListByBox")
    List<com.igool.rpc.db.model.thrift.BusinessInfo> getBusinessInfoListByBox(
        @ThriftField(value=1, name="box", requiredness=Requiredness.NONE) final String box,
        @ThriftField(value=2, name="deliveryId", requiredness=Requiredness.NONE) final String deliveryId,
        @ThriftField(value=3, name="deliveryCode", requiredness=Requiredness.NONE) final String deliveryCode
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "delDeliveryRel")
    void delDeliveryRel(
        @ThriftField(value=1, name="ids", requiredness=Requiredness.NONE) final String ids,
        @ThriftField(value=2, name="box", requiredness=Requiredness.NONE) final String box,
        @ThriftField(value=3, name="deliveryId", requiredness=Requiredness.NONE) final String deliveryId,
        @ThriftField(value=4, name="userId", requiredness=Requiredness.NONE) final int userId,
        @ThriftField(value=5, name="deliveryCode", requiredness=Requiredness.NONE) final String deliveryCode
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getBusinessInfoListForImage")
    List<com.igool.rpc.db.model.thrift.BusinessInfo> getBusinessInfoListForImage(
        @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo,
        @ThriftField(value=2, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
        @ThriftField(value=3, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getBusinessInfoListForImageCount")
    long getBusinessInfoListForImageCount(
        @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo,
        @ThriftField(value=2, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
        @ThriftField(value=3, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "updateQsZl")
    void updateQsZl(
        @ThriftField(value=1, name="businessId", requiredness=Requiredness.NONE) final String businessId,
        @ThriftField(value=2, name="businessDetailIds", requiredness=Requiredness.NONE) final String businessDetailIds,
        @ThriftField(value=3, name="userId", requiredness=Requiredness.NONE) final int userId,
        @ThriftField(value=4, name="fileId", requiredness=Requiredness.NONE) final String fileId
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "addBusinessQszl")
    void addBusinessQszl(
        @ThriftField(value=1, name="lsh", requiredness=Requiredness.NONE) final String lsh,
        @ThriftField(value=2, name="userId", requiredness=Requiredness.NONE) final String userId
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "findBusinessIdAndImageIdAndBusinessTypeIdByLsh")
    List<com.igool.rpc.db.model.thrift.BusinessImageDTO> findBusinessIdAndImageIdAndBusinessTypeIdByLsh(
        @ThriftField(value=1, name="lsh", requiredness=Requiredness.NONE) final String lsh
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "addFileInfo")
    int addFileInfo(
        @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getJxrwqsList")
    List<com.igool.rpc.db.model.thrift.Jjtj> getJxrwqsList(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "findFileInfoByBox")
    List<com.igool.rpc.db.model.thrift.BusinessInfo> findFileInfoByBox(
        @ThriftField(value=1, name="box", requiredness=Requiredness.NONE) final String box
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "findNotSignCodeByBox")
    List<String> findNotSignCodeByBox(
        @ThriftField(value=1, name="box", requiredness=Requiredness.NONE) final String box
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getNewLsmxListCount")
    long getNewLsmxListCount(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
        @ThriftField(value=3, name="jjlx", requiredness=Requiredness.NONE) final int jjlx,
        @ThriftField(value=4, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
        @ThriftField(value=5, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getNewDamxListCount")
    long getNewDamxListCount(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
        @ThriftField(value=3, name="jjlx", requiredness=Requiredness.NONE) final int jjlx,
        @ThriftField(value=4, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
        @ThriftField(value=5, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
    ) throws org.apache.thrift.TException;
}