// Generated by swift-generator from dzda/cacheservice.thrift

package com.igool.rpc.db.service.thrift;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.service.*;
import com.google.common.util.concurrent.ListenableFuture;
import java.io.*;
import java.util.*;


@ThriftService("CacheService")
public interface CacheService extends Closeable
{
    @ThriftService("CacheService")
    public interface Async extends Closeable
    {
        void close();

        @ThriftMethod(value = "getBusinessType")
        ListenableFuture<Map<String, String>> getBusinessType();

        @ThriftMethod(value = "getPlatType")
        ListenableFuture<Map<String, String>> getPlatType();
    }
    void close();


    @ThriftMethod(value = "getBusinessType")
    Map<String, String> getBusinessType() throws org.apache.thrift.TException;

    @ThriftMethod(value = "getPlatType")
    Map<String, String> getPlatType() throws org.apache.thrift.TException;
}