// Generated by swift-generator from dzda/imageinfoservice.thrift

package com.igool.rpc.db.service.thrift;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.service.*;
import com.google.common.util.concurrent.ListenableFuture;
import java.io.*;
import java.util.*;


@ThriftService("ImageInfoService")
public interface ImageInfoService extends Closeable
{
    @ThriftService("ImageInfoService")
    public interface Async extends Closeable
    {
        void close();

        @ThriftMethod(value = "addOrUpdataInfoByDTO")
        ListenableFuture<Void> addOrUpdataInfoByDTO(
            @ThriftField(value=1, name="imagePhotoRelDTO", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.ImagePhotoRelDTO imagePhotoRelDTO
        );

        @ThriftMethod(value = "updataImageStatus")
        ListenableFuture<Void> updataImageStatus(
            @ThriftField(value=1, name="lsh", requiredness=Requiredness.NONE) final String lsh,
            @ThriftField(value=2, name="status", requiredness=Requiredness.NONE) final int status
        );

        @ThriftMethod(value = "findBusinessImageCount")
        ListenableFuture<com.igool.rpc.db.model.thrift.BusinessImageCount> findBusinessImageCount(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime
        );

        @ThriftMethod(value = "ajaxStreamNum")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.ImageInfo>> ajaxStreamNum(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime
        );

        @ThriftMethod(value = "fileCodeDetail")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.BusinessInfo>> fileCodeDetail(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime
        );

        @ThriftMethod(value = "userImageCount")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.UserImageCount>> userImageCount(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime
        );

        @ThriftMethod(value = "businessNumDetailByDateAndUserId")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.ImageInfo>> businessNumDetailByDateAndUserId(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
            @ThriftField(value=3, name="userId", requiredness=Requiredness.NONE) final String userId
        );

        @ThriftMethod(value = "driverNumDetail")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.BusinessInfo>> driverNumDetail(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
            @ThriftField(value=3, name="userId", requiredness=Requiredness.NONE) final String userId
        );

        @ThriftMethod(value = "findImagePhotoNumByDate")
        ListenableFuture<Integer> findImagePhotoNumByDate(
            @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime
        );
    }
    void close();


    @ThriftMethod(value = "addOrUpdataInfoByDTO")
    void addOrUpdataInfoByDTO(
        @ThriftField(value=1, name="imagePhotoRelDTO", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.ImagePhotoRelDTO imagePhotoRelDTO
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "updataImageStatus")
    void updataImageStatus(
        @ThriftField(value=1, name="lsh", requiredness=Requiredness.NONE) final String lsh,
        @ThriftField(value=2, name="status", requiredness=Requiredness.NONE) final int status
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "findBusinessImageCount")
    com.igool.rpc.db.model.thrift.BusinessImageCount findBusinessImageCount(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "ajaxStreamNum")
    List<com.igool.rpc.db.model.thrift.ImageInfo> ajaxStreamNum(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "fileCodeDetail")
    List<com.igool.rpc.db.model.thrift.BusinessInfo> fileCodeDetail(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "userImageCount")
    List<com.igool.rpc.db.model.thrift.UserImageCount> userImageCount(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "businessNumDetailByDateAndUserId")
    List<com.igool.rpc.db.model.thrift.ImageInfo> businessNumDetailByDateAndUserId(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
        @ThriftField(value=3, name="userId", requiredness=Requiredness.NONE) final String userId
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "driverNumDetail")
    List<com.igool.rpc.db.model.thrift.BusinessInfo> driverNumDetail(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime,
        @ThriftField(value=3, name="userId", requiredness=Requiredness.NONE) final String userId
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "findImagePhotoNumByDate")
    int findImagePhotoNumByDate(
        @ThriftField(value=1, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=2, name="endTime", requiredness=Requiredness.NONE) final String endTime
    ) throws org.apache.thrift.TException;
}