// Generated by swift-generator from dzda/userinfoservice.thrift

package com.igool.rpc.db.service.thrift;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.service.*;
import com.google.common.util.concurrent.ListenableFuture;
import java.io.*;
import java.util.*;


@ThriftService("RoleResourceService")
public interface RoleResourceService extends Closeable
{
    @ThriftService("RoleResourceService")
    public interface Async extends Closeable
    {
        void close();

        @ThriftMethod(value = "getAdminPermissionList")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.Resource>> getAdminPermissionList(
            @ThriftField(value=1, name="userinfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.UserInfo userinfo
        );

        @ThriftMethod(value = "getResourceList")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.Resource>> getResourceList();

        @ThriftMethod(value = "getResourceIdsByRoleId")
        ListenableFuture<List<Integer>> getResourceIdsByRoleId(
            @ThriftField(value=1, name="roleId", requiredness=Requiredness.NONE) final int roleId
        );

        @ThriftMethod(value = "addResource")
        ListenableFuture<Void> addResource(
            @ThriftField(value=1, name="resource", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.Resource resource
        );

        @ThriftMethod(value = "findResourceById")
        ListenableFuture<com.igool.rpc.db.model.thrift.Resource> findResourceById(
            @ThriftField(value=1, name="id", requiredness=Requiredness.NONE) final int id
        );

        @ThriftMethod(value = "updateResource")
        ListenableFuture<Void> updateResource(
            @ThriftField(value=1, name="resource", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.Resource resource
        );

        @ThriftMethod(value = "saveRoleSource")
        ListenableFuture<Void> saveRoleSource(
            @ThriftField(value=1, name="sourceIds", requiredness=Requiredness.NONE) final String sourceIds,
            @ThriftField(value=2, name="roleId", requiredness=Requiredness.NONE) final int roleId,
            @ThriftField(value=3, name="createUserId", requiredness=Requiredness.NONE) final int createUserId
        );

        @ThriftMethod(value = "addRoleResource")
        ListenableFuture<Void> addRoleResource(
            @ThriftField(value=1, name="sourceIds", requiredness=Requiredness.NONE) final List<Integer> sourceIds,
            @ThriftField(value=2, name="roleId", requiredness=Requiredness.NONE) final int roleId,
            @ThriftField(value=3, name="createUserId", requiredness=Requiredness.NONE) final int createUserId
        );

        @ThriftMethod(value = "deleteRoleResource")
        ListenableFuture<Void> deleteRoleResource(
            @ThriftField(value=1, name="sourceIds", requiredness=Requiredness.NONE) final List<Integer> sourceIds,
            @ThriftField(value=2, name="roleId", requiredness=Requiredness.NONE) final int roleId,
            @ThriftField(value=3, name="createUserId", requiredness=Requiredness.NONE) final int createUserId
        );
    }
    void close();


    @ThriftMethod(value = "getAdminPermissionList")
    List<com.igool.rpc.db.model.thrift.Resource> getAdminPermissionList(
        @ThriftField(value=1, name="userinfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.UserInfo userinfo
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getResourceList")
    List<com.igool.rpc.db.model.thrift.Resource> getResourceList() throws org.apache.thrift.TException;

    @ThriftMethod(value = "getResourceIdsByRoleId")
    List<Integer> getResourceIdsByRoleId(
        @ThriftField(value=1, name="roleId", requiredness=Requiredness.NONE) final int roleId
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "addResource")
    void addResource(
        @ThriftField(value=1, name="resource", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.Resource resource
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "findResourceById")
    com.igool.rpc.db.model.thrift.Resource findResourceById(
        @ThriftField(value=1, name="id", requiredness=Requiredness.NONE) final int id
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "updateResource")
    void updateResource(
        @ThriftField(value=1, name="resource", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.Resource resource
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "saveRoleSource")
    void saveRoleSource(
        @ThriftField(value=1, name="sourceIds", requiredness=Requiredness.NONE) final String sourceIds,
        @ThriftField(value=2, name="roleId", requiredness=Requiredness.NONE) final int roleId,
        @ThriftField(value=3, name="createUserId", requiredness=Requiredness.NONE) final int createUserId
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "addRoleResource")
    void addRoleResource(
        @ThriftField(value=1, name="sourceIds", requiredness=Requiredness.NONE) final List<Integer> sourceIds,
        @ThriftField(value=2, name="roleId", requiredness=Requiredness.NONE) final int roleId,
        @ThriftField(value=3, name="createUserId", requiredness=Requiredness.NONE) final int createUserId
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "deleteRoleResource")
    void deleteRoleResource(
        @ThriftField(value=1, name="sourceIds", requiredness=Requiredness.NONE) final List<Integer> sourceIds,
        @ThriftField(value=2, name="roleId", requiredness=Requiredness.NONE) final int roleId,
        @ThriftField(value=3, name="createUserId", requiredness=Requiredness.NONE) final int createUserId
    ) throws org.apache.thrift.TException;
}