// Generated by swift-generator from dzda/roleservice.thrift

package com.igool.rpc.db.service.thrift;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.service.*;
import com.google.common.util.concurrent.ListenableFuture;
import java.io.*;
import java.util.*;


@ThriftService("RoleService")
public interface RoleService extends Closeable
{
    @ThriftService("RoleService")
    public interface Async extends Closeable
    {
        void close();

        @ThriftMethod(value = "getUserRoleList")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.Roles>> getUserRoleList(
            @ThriftField(value=1, name="uid", requiredness=Requiredness.NONE) final int uid
        );

        @ThriftMethod(value = "getRoleSourceList")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.Resource>> getRoleSourceList(
            @ThriftField(value=1, name="roleId", requiredness=Requiredness.NONE) final int roleId
        );

        @ThriftMethod(value = "getRoleList")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.Roles>> getRoleList(
            @ThriftField(value=1, name="role", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.Roles role,
            @ThriftField(value=2, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
            @ThriftField(value=3, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
        );

        @ThriftMethod(value = "getRoleListCount")
        ListenableFuture<Long> getRoleListCount(
            @ThriftField(value=1, name="role", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.Roles role,
            @ThriftField(value=2, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
            @ThriftField(value=3, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
        );

        @ThriftMethod(value = "addRole")
        ListenableFuture<Void> addRole(
            @ThriftField(value=1, name="role", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.Roles role
        );

        @ThriftMethod(value = "ajaxVerifyName")
        ListenableFuture<com.igool.rpc.db.model.thrift.Roles> ajaxVerifyName(
            @ThriftField(value=1, name="name", requiredness=Requiredness.NONE) final String name
        );

        @ThriftMethod(value = "updateRole")
        ListenableFuture<Void> updateRole(
            @ThriftField(value=1, name="role", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.Roles role
        );

        @ThriftMethod(value = "findRoleByRid")
        ListenableFuture<com.igool.rpc.db.model.thrift.Roles> findRoleByRid(
            @ThriftField(value=1, name="roleId", requiredness=Requiredness.NONE) final int roleId
        );

        @ThriftMethod(value = "getRoleIdsByUserId")
        ListenableFuture<List<Integer>> getRoleIdsByUserId(
            @ThriftField(value=1, name="userId", requiredness=Requiredness.NONE) final int userId
        );

        @ThriftMethod(value = "saveUserRole")
        ListenableFuture<Void> saveUserRole(
            @ThriftField(value=1, name="roleIds", requiredness=Requiredness.NONE) final String roleIds,
            @ThriftField(value=2, name="userId", requiredness=Requiredness.NONE) final int userId,
            @ThriftField(value=3, name="createUserId", requiredness=Requiredness.NONE) final int createUserId
        );

        @ThriftMethod(value = "addUserRole")
        ListenableFuture<Void> addUserRole(
            @ThriftField(value=1, name="roleIds", requiredness=Requiredness.NONE) final List<Integer> roleIds,
            @ThriftField(value=2, name="userId", requiredness=Requiredness.NONE) final int userId,
            @ThriftField(value=3, name="createUserId", requiredness=Requiredness.NONE) final int createUserId
        );

        @ThriftMethod(value = "deleteUserRole")
        ListenableFuture<Void> deleteUserRole(
            @ThriftField(value=1, name="roleIds", requiredness=Requiredness.NONE) final List<Integer> roleIds,
            @ThriftField(value=2, name="userId", requiredness=Requiredness.NONE) final int userId,
            @ThriftField(value=3, name="createUserId", requiredness=Requiredness.NONE) final int createUserId
        );
    }
    void close();


    @ThriftMethod(value = "getUserRoleList")
    List<com.igool.rpc.db.model.thrift.Roles> getUserRoleList(
        @ThriftField(value=1, name="uid", requiredness=Requiredness.NONE) final int uid
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getRoleSourceList")
    List<com.igool.rpc.db.model.thrift.Resource> getRoleSourceList(
        @ThriftField(value=1, name="roleId", requiredness=Requiredness.NONE) final int roleId
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getRoleList")
    List<com.igool.rpc.db.model.thrift.Roles> getRoleList(
        @ThriftField(value=1, name="role", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.Roles role,
        @ThriftField(value=2, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
        @ThriftField(value=3, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getRoleListCount")
    long getRoleListCount(
        @ThriftField(value=1, name="role", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.Roles role,
        @ThriftField(value=2, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
        @ThriftField(value=3, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "addRole")
    void addRole(
        @ThriftField(value=1, name="role", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.Roles role
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "ajaxVerifyName")
    com.igool.rpc.db.model.thrift.Roles ajaxVerifyName(
        @ThriftField(value=1, name="name", requiredness=Requiredness.NONE) final String name
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "updateRole")
    void updateRole(
        @ThriftField(value=1, name="role", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.Roles role
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "findRoleByRid")
    com.igool.rpc.db.model.thrift.Roles findRoleByRid(
        @ThriftField(value=1, name="roleId", requiredness=Requiredness.NONE) final int roleId
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getRoleIdsByUserId")
    List<Integer> getRoleIdsByUserId(
        @ThriftField(value=1, name="userId", requiredness=Requiredness.NONE) final int userId
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "saveUserRole")
    void saveUserRole(
        @ThriftField(value=1, name="roleIds", requiredness=Requiredness.NONE) final String roleIds,
        @ThriftField(value=2, name="userId", requiredness=Requiredness.NONE) final int userId,
        @ThriftField(value=3, name="createUserId", requiredness=Requiredness.NONE) final int createUserId
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "addUserRole")
    void addUserRole(
        @ThriftField(value=1, name="roleIds", requiredness=Requiredness.NONE) final List<Integer> roleIds,
        @ThriftField(value=2, name="userId", requiredness=Requiredness.NONE) final int userId,
        @ThriftField(value=3, name="createUserId", requiredness=Requiredness.NONE) final int createUserId
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "deleteUserRole")
    void deleteUserRole(
        @ThriftField(value=1, name="roleIds", requiredness=Requiredness.NONE) final List<Integer> roleIds,
        @ThriftField(value=2, name="userId", requiredness=Requiredness.NONE) final int userId,
        @ThriftField(value=3, name="createUserId", requiredness=Requiredness.NONE) final int createUserId
    ) throws org.apache.thrift.TException;
}