// Generated by swift-generator from dzda/transferservice.thrift

package com.igool.rpc.db.service.thrift;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.service.*;
import com.google.common.util.concurrent.ListenableFuture;
import java.io.*;
import java.util.*;


@ThriftService("TransferService")
public interface TransferService extends Closeable
{
    @ThriftService("TransferService")
    public interface Async extends Closeable
    {
        void close();

        @ThriftMethod(value = "findNativeBusinessInfo")
        ListenableFuture<com.igool.rpc.db.model.thrift.BusinessInfo> findNativeBusinessInfo(
            @ThriftField(value=1, name="lsh", requiredness=Requiredness.NONE) final String lsh
        );

        @ThriftMethod(value = "findDeliveryInfoByPcCode")
        ListenableFuture<com.igool.rpc.db.model.thrift.DeliveryInfo> findDeliveryInfoByPcCode(
            @ThriftField(value=1, name="pcCode", requiredness=Requiredness.NONE) final String pcCode
        );

        @ThriftMethod(value = "getDeliveryListBza")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.DeliveryInfo>> getDeliveryListBza(
            @ThriftField(value=1, name="pcCode", requiredness=Requiredness.NONE) final String pcCode,
            @ThriftField(value=2, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=3, name="endTime", requiredness=Requiredness.NONE) final String endTime,
            @ThriftField(value=4, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
            @ThriftField(value=5, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
        );

        @ThriftMethod(value = "getDeliveryListCountBza")
        ListenableFuture<Long> getDeliveryListCountBza(
            @ThriftField(value=1, name="pcCode", requiredness=Requiredness.NONE) final String pcCode,
            @ThriftField(value=2, name="startTime", requiredness=Requiredness.NONE) final String startTime,
            @ThriftField(value=3, name="endTime", requiredness=Requiredness.NONE) final String endTime,
            @ThriftField(value=4, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
            @ThriftField(value=5, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
        );

        @ThriftMethod(value = "findBusinessInfoByPcCodeAndLszt")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.BusinessInfo>> findBusinessInfoByPcCodeAndLszt(
            @ThriftField(value=1, name="pcCode", requiredness=Requiredness.NONE) final String pcCode,
            @ThriftField(value=2, name="lszt", requiredness=Requiredness.NONE) final int lszt
        );

        @ThriftMethod(value = "BToASign")
        ListenableFuture<Void> BToASign(
            @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo,
            @ThriftField(value=2, name="pcCode", requiredness=Requiredness.NONE) final String pcCode,
            @ThriftField(value=3, name="userId", requiredness=Requiredness.NONE) final int userId
        );

        @ThriftMethod(value = "findAllFileIdsByCkStatus")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.FileId>> findAllFileIdsByCkStatus(
            @ThriftField(value=1, name="ckStatus", requiredness=Requiredness.NONE) final int ckStatus
        );

        @ThriftMethod(value = "findAllForFileCode")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.FileId>> findAllForFileCode();

        @ThriftMethod(value = "findAllForBox")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.FileId>> findAllForBox();

        @ThriftMethod(value = "findAllForFileCodeCount")
        ListenableFuture<Integer> findAllForFileCodeCount();

        @ThriftMethod(value = "findAllForBoxCount")
        ListenableFuture<Integer> findAllForBoxCount();

        @ThriftMethod(value = "findForFileCode")
        ListenableFuture<List<com.igool.rpc.db.model.thrift.FileId>> findForFileCode(
            @ThriftField(value=1, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
            @ThriftField(value=2, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
        );
    }
    void close();


    @ThriftMethod(value = "findNativeBusinessInfo")
    com.igool.rpc.db.model.thrift.BusinessInfo findNativeBusinessInfo(
        @ThriftField(value=1, name="lsh", requiredness=Requiredness.NONE) final String lsh
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "findDeliveryInfoByPcCode")
    com.igool.rpc.db.model.thrift.DeliveryInfo findDeliveryInfoByPcCode(
        @ThriftField(value=1, name="pcCode", requiredness=Requiredness.NONE) final String pcCode
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getDeliveryListBza")
    List<com.igool.rpc.db.model.thrift.DeliveryInfo> getDeliveryListBza(
        @ThriftField(value=1, name="pcCode", requiredness=Requiredness.NONE) final String pcCode,
        @ThriftField(value=2, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=3, name="endTime", requiredness=Requiredness.NONE) final String endTime,
        @ThriftField(value=4, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
        @ThriftField(value=5, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "getDeliveryListCountBza")
    long getDeliveryListCountBza(
        @ThriftField(value=1, name="pcCode", requiredness=Requiredness.NONE) final String pcCode,
        @ThriftField(value=2, name="startTime", requiredness=Requiredness.NONE) final String startTime,
        @ThriftField(value=3, name="endTime", requiredness=Requiredness.NONE) final String endTime,
        @ThriftField(value=4, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
        @ThriftField(value=5, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "findBusinessInfoByPcCodeAndLszt")
    List<com.igool.rpc.db.model.thrift.BusinessInfo> findBusinessInfoByPcCodeAndLszt(
        @ThriftField(value=1, name="pcCode", requiredness=Requiredness.NONE) final String pcCode,
        @ThriftField(value=2, name="lszt", requiredness=Requiredness.NONE) final int lszt
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "BToASign")
    void BToASign(
        @ThriftField(value=1, name="businessInfo", requiredness=Requiredness.NONE) final com.igool.rpc.db.model.thrift.BusinessInfo businessInfo,
        @ThriftField(value=2, name="pcCode", requiredness=Requiredness.NONE) final String pcCode,
        @ThriftField(value=3, name="userId", requiredness=Requiredness.NONE) final int userId
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "findAllFileIdsByCkStatus")
    List<com.igool.rpc.db.model.thrift.FileId> findAllFileIdsByCkStatus(
        @ThriftField(value=1, name="ckStatus", requiredness=Requiredness.NONE) final int ckStatus
    ) throws org.apache.thrift.TException;

    @ThriftMethod(value = "findAllForFileCode")
    List<com.igool.rpc.db.model.thrift.FileId> findAllForFileCode() throws org.apache.thrift.TException;

    @ThriftMethod(value = "findAllForBox")
    List<com.igool.rpc.db.model.thrift.FileId> findAllForBox() throws org.apache.thrift.TException;

    @ThriftMethod(value = "findAllForFileCodeCount")
    int findAllForFileCodeCount() throws org.apache.thrift.TException;

    @ThriftMethod(value = "findAllForBoxCount")
    int findAllForBoxCount() throws org.apache.thrift.TException;

    @ThriftMethod(value = "findForFileCode")
    List<com.igool.rpc.db.model.thrift.FileId> findForFileCode(
        @ThriftField(value=1, name="startIndex", requiredness=Requiredness.NONE) final int startIndex,
        @ThriftField(value=2, name="pageSize", requiredness=Requiredness.NONE) final int pageSize
    ) throws org.apache.thrift.TException;
}